#!/usr/bin/env bash

#*******************************************************************************
#
# Bare Conductive Pi Cap Simple Touch Utility C++ Example Runner
# --------------------------------------------------------------
#
# run - compiles and runs simple-touch
#
# Written by Stefan Dzisiewski-Smith
#
# This work is licensed under a MIT license https://opensource.org/licenses/MIT
#
# Copyright (c) 2016, Bare Conductive
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#*******************************************************************************

# make sure we're cd-ed into the script directory
cd "$(dirname "$(readlink -f "${BASH_SOURCE}")")" || exit

# make (& grab the return value)
make --quiet
make_return_value=$?

# put back any of the quotes that BASH removed
# so we can show the user what we're running underneath
execute_and_echo() {
    args=''
    whitespace="[[:space:]]"
    for i in "$@"
    do
        if [[ $i =~ $whitespace ]]
        then
            i=\"$i\"
        fi
        args+="$i ";
    done
    echo "\$ $args"
    bash -c "$args"
}

# only run the code if make succeeded
if [[ $make_return_value -eq 0 ]]; then
    # add sudo if we need to - and pass all arguments to the target
    if [[ $EUID -ne 0 ]]; then
        sudo pkill fluidsynth
	sudo ./midi | fluidsynth -f ./config.txt -a alsa /usr/share/sounds/sf2/FluidR3_GM.sf2
    else
        pkill fluidsynth
	./midi | fluidsynth -f ./config.txt -a alsa /usr/share/sounds/sf2/FluidR3_GM.sf2
    fi
fi
